"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os

from setuptools import setup


def resource_files(root_dir, strip_prefix):
    files = []
    for directory, _, filenames in os.walk(root_dir):
        for filename in filenames:
            file_path = os.path.join(directory, filename)
            target_path = os.path.relpath(file_path, strip_prefix)
            files.append((os.path.dirname(target_path), [file_path]))
    return files


APP = ['main.py']
DATA_FILES = resource_files('novaimgs', '.')
OPTIONS = {"argv_emulation": True,
           'packages': ['pyautogui', 'pygetwindow', 'numpy', 'cv2'],
           # 'includes': ['PyInstaller.hooks.hook-django.template.loaders', 'rubicon']
           'excludes': ['rubicon']
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
