"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [("novaimgs", ["novaimgs/*.png"])]
OPTIONS = {"argv_emulation": True,
           'packages': ['pyautogui', 'pygetwindow', 'numpy', 'cv2'],
           # 'includes': ['PyInstaller.hooks.hook-django.template.loaders', 'rubicon']
           'excludes': ['rubicon']
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
