"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ["novaimgs/"]
OPTIONS = {"argv_emulation": True,
           "plist": {
               "CFBundleName": "AutoNova",  # 应用名
               "CFBundleDisplayName": "AutoNova",  # 应用显示名
               "CFBundleVersion": "1.0.0",  # 应用版本号
               "CFBundleIdentifier": "AutoNova",  # 应用包名、唯一标识
           }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
