name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 更新到 v3

    - name: Set up Python
      uses: actions/setup-python@v4  # 更新到 v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app opencv-python-headless pygetwindow pyautogui numpy
    - name: Build with py2app
      run: |
        python setup.py py2app

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AutoNova-MacOS
        path: dist/
